name: Frontend Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: ./Forntend
        run: npm install

      - name: Build Frontend
        working-directory: ./Forntend
        run: npm run build

      - name: Verify Build
        run: |
          echo "Current Directory:"
          pwd

          echo "Repository Contents:"
          ls -la

          echo "Frontend Folder:"
          ls -la Forntend

          echo "Dist Folder:"
          ls -la Forntend/dist

      # Remove old build on EC2
      - name: Clean old dist on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p /home/ubuntu/frontend/Forntend
            rm -rf /home/ubuntu/frontend/Forntend/dist

      # Upload build
      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_KEY }}
          source: "Forntend/dist/*"
          target: "/home/ubuntu/frontend/Forntend"
          overwrite: true
          debug: true

      - name: Deployment Complete
        run: echo "Frontend deployed successfully."
